#! /usr/bin/env python
#
import os
import array
import sys
import csv

#-----------------------------------------------------------------------------#
#                                MAIN PROGRAM
#-----------------------------------------------------------------------------#
#
def main():
	log_list = []
	log_list_noext = []
	last_line_list = []

	# Open output file.
	nameOutputFile = "lastLogLines.out"
	foOutput = open(nameOutputFile, "w",newline='')

	# Get list of log files in directory.
	#
	print ("\nLog files to process...")
	log_count = 0
	for dirpath, dirnames, filenames in os.walk('.'):
		for name in filenames:
			root, ext = os.path.splitext(name) 
			if dirpath == ".":
				if ext == ".log":
					log_list.append(name)
					log_list_noext.append(root)
					log_count = log_count + 1
					print(log_count, " ", root, ext)

	# Read one LOG file to get the first two lines
	#   and write the to the output file.
	#
	with open(log_list[0]) as f1:
		headerLine = f1.readline()
		unitsLine = f1.readline()
		f1.close()
	foOutput.write(headerLine)
	foOutput.write(unitsLine)

	# Read through to the last line of each LOG file
	#   and write it to the Output file object.
	for fname in log_list:
		with open(fname) as f:
			for line in f:
					pass
			last_line = line
			last_line_list.append(last_line)
			foOutput.write(last_line)

#--- End main() ---#

if __name__ == "__main__":
	main()
